# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- fix/SerialMultiPlatform

strategy:
  matrix:
    ubuntu:
      imageName: 'ubuntu-16.04'
    mac-High-Sierra:
      imageName: 'macos-10.13'
    mac-Mojave:
      imageName: 'macos-10.14'
    win-2019:
       imageName: 'windows-2019'
    indows-core:
       imagename: 'win1803'

# images/agents : https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops


pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run EP
  displayName: 'get execuion policy'

- script: |
    npm run build
  displayName: 'npm build'

- script: |
    npm run package-prep
  displayName: 'npm prepare for vscode package'

- script: |
    npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true

- script: |
    npm run package
  displayName: 'npm package'

- task: CopyFiles@1
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
    
      *.vsix
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
