name: Compile Native Modules

on: [push]

jobs:
  build:
    name: Compile ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "12"

      - name: Install Windows Build Tools
        if: matrix.os == 'windows-latest'
        run: |
          npm install -g node-gyp

      - name: Install Dependencies
        shell: bash
        run: |
          npm install --ignore-scripts --no-audit
          npm install serialport node-abi --no-audit
          npm install npx --no-audit

      - name: Rebuild Bindings
        uses: ./.github/actions/compile-modules-action
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Git Status
        run: git status -vv
