name: Deploy PyMakr

on:
  push:
    branches:
      - master
      - alpha
      - 2.x

jobs:
  deploy:
    environment: vsce-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - run: npm ci

      - name: Publish
        # for testing, add --dry-run --debug
        run: npx semantic-release --dry-run
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}